# Generated by Django 5.0.2 on 2024-02-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardschool', '0002_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_min_students',
        ),
        migrations.AddField(
            model_name='product',
            name='max_students',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='min_students',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
